Page({
  data:{
    region:[],
    customItem:"all",
    swiper:[
      {
        href:"https://wap.zebrasports.cn/upload/sysbase/20190426/5cc2b9f521ff98.12816673s.jpg",
        img:"https://wap.zebrasports.cn/upload/sysbase/20190426/5cc2b9f521ff98.12816673s.jpg"
      },
      {
        href:"https://wap.zebrasports.cn/upload/sysbase/20190426/5cc2b9f521ff98.12816673s.jpg",
        img:"https://wap.zebrasports.cn/upload/sysbase/20190426/5cc2b9f521ff98.12816673s.jpg"
      },
      {
        href:"https://wap.zebrasports.cn/upload/sysbase/20190426/5cc2b9f521ff98.12816673s.jpg",
        img:"https://wap.zebrasports.cn/upload/sysbase/20190426/5cc2b9f521ff98.12816673s.jpg"
      },
      {
        href:"https://wap.zebrasports.cn/upload/sysbase/20190426/5cc2b9f521ff98.12816673s.jpg",
        img:"https://wap.zebrasports.cn/upload/sysbase/20190426/5cc2b9f521ff98.12816673s.jpg"
      }
    ],
    nav:[
      [
        {
          href:"https://wap.zebrasports.cn/index.php/Home/Course/discountslist.html",
          img:"https://wap.zebrasports.cn/Public/home/images/tejia.png",
          title:"特价"
        },
        {
          href:"https://wap.zebrasports.cn/index.php/Home/Index/index.html",
          img:"https://wap.zebrasports.cn/Public/home/images/club.png",
          title:"俱乐部"
        },
        {
          href:"https://wap.zebrasports.cn/index.php/Home/Competition/competitionlist.html",
          img:"https://wap.zebrasports.cn/Public/home/images/competition.png",
          title:"比赛"
        },
        {
          href:"https://wap.zebrasports.cn/index.php/Home/Course/courselist.html",
          img:"https://wap.zebrasports.cn/Public/home/images/curriculum.png",
          title:"课程"
        }
      ],
      [
        {
          href:"https://wap.zebrasports.cn/index.php/Home/Bargain/bargainlist.html",
          img:"https://wap.zebrasports.cn/Public/home/images/bargain.png",
          title:"砍价"
        },
        {
          href:"https://wap.zebrasports.cn/index.php/Home/Collage/collagelist.html",
          img:"https://wap.zebrasports.cn/Public/home/images/pintuan.png",
          title:"拼团"
        },
        {
          href:"https://wap.zebrasports.cn/index.php/Home/Marketing/marketlist.html",
          img:"https://wap.zebrasports.cn/Public/home/images/fanxian.png",
          title:"返现"
        },
        {
          href:"https://wap.zebrasports.cn/index.php/Home/Activity/cheerActivitylist.html",
          img:"https://wap.zebrasports.cn/Public/home/images/zhuwei.png",
          title:"助威"
        }
      ]
    ],
    sport:[
      {
        href:"https://wap.zebrasports.cn/index.php/Home/Index/index.html?sportid=0&sportname=全部",
        img:"https://wap.zebrasports.cn/Public/home/images/movementitems-more.png",
        title:"全部"
      },
      {
        href:"https://wap.zebrasports.cn/index.php/Home/Index/index.html?sportid=0&sportname=全部",
        img:"https://wap.zebrasports.cn/Public/home/images/movementitems-more.png",
        title:"全部"
      },
      {
        href:"https://wap.zebrasports.cn/index.php/Home/Index/index.html?sportid=0&sportname=全部",
        img:"https://wap.zebrasports.cn/Public/home/images/movementitems-more.png",
        title:"全部"
      },
      {
        href:"https://wap.zebrasports.cn/index.php/Home/Index/index.html?sportid=0&sportname=全部",
        img:"https://wap.zebrasports.cn/Public/home/images/movementitems-more.png",
        title:"全部"
      },
      {
        href:"https://wap.zebrasports.cn/index.php/Home/Index/index.html?sportid=0&sportname=全部",
        img:"https://wap.zebrasports.cn/Public/home/images/movementitems-more.png",
        title:"全部"
      },
    ]
  },
  onShow: function(e){

  },
  bindRegionChange:function(e){
    console.log(e);
    this.setData({
      region: e.detail.value
    })
  }
})